version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: software.amazon.awssdk:bundle
    versions:
    - 2.15.72
    - 2.15.73
    - 2.15.74
    - 2.15.75
    - 2.15.76
    - 2.15.77
    - 2.15.78
    - 2.15.79
    - 2.15.80
    - 2.15.81
    - 2.15.82
    - 2.16.0
    - 2.16.1
    - 2.16.10
    - 2.16.11
    - 2.16.12
    - 2.16.13
    - 2.16.14
    - 2.16.16
    - 2.16.17
    - 2.16.18
    - 2.16.19
    - 2.16.2
    - 2.16.20
    - 2.16.21
    - 2.16.23
    - 2.16.24
    - 2.16.25
    - 2.16.26
    - 2.16.28
    - 2.16.29
    - 2.16.3
    - 2.16.30
    - 2.16.31
    - 2.16.33
    - 2.16.34
    - 2.16.35
    - 2.16.36
    - 2.16.37
    - 2.16.38
    - 2.16.39
    - 2.16.4
    - 2.16.40
    - 2.16.41
    - 2.16.42
    - 2.16.43
    - 2.16.44
    - 2.16.45
    - 2.16.46
    - 2.16.47
    - 2.16.48
    - 2.16.49
    - 2.16.5
    - 2.16.6
    - 2.16.7
    - 2.16.8
    - 2.16.9
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: software.amazon.kinesis:amazon-kinesis-client
    versions:
    - 2.3.3
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - 4.9.0
