type = "fixed"
message = "Fixed issue with Palo Alto Global Protect logs parsing last 5 fields incorrectly."

issues = ["1327", "Graylog2/graylog2-server#14363"]
pulls = ["1328"]

contributors = ["@giveen"]