package org.graylog.integrations.inputs.paloalto.types;

import com.google.common.collect.ImmutableMap;

public class ThreatMessageMapping implements MessageMapping {

    public static final ImmutableMap<Integer, FieldDescription> MAP = new ImmutableMap.Builder<Integer, FieldDescription>()
            .put(1, FieldDescription.create("pa_time_received", FieldDescription.FIELD_TYPE.STRING))
            .put(2, FieldDescription.create("serial_number", FieldDescription.FIELD_TYPE.STRING))
            .put(3, FieldDescription.create("pa_type", FieldDescription.FIELD_TYPE.STRING))
            .put(4, FieldDescription.create("threat_type", FieldDescription.FIELD_TYPE.STRING))
            .put(5, FieldDescription.create("pa_unknown", FieldDescription.FIELD_TYPE.STRING))
            .put(6, FieldDescription.create("generated_time", FieldDescription.FIELD_TYPE.STRING))
            .put(7, FieldDescription.create("src_ip", FieldDescription.FIELD_TYPE.STRING))
            .put(8, FieldDescription.create("dest_ip", FieldDescription.FIELD_TYPE.STRING))
            .put(9, FieldDescription.create("nat_src_ip", FieldDescription.FIELD_TYPE.STRING))
            .put(10, FieldDescription.create("nat_dest_ip", FieldDescription.FIELD_TYPE.STRING))
            .put(11, FieldDescription.create("pa_rule_name", FieldDescription.FIELD_TYPE.STRING))
            .put(12, FieldDescription.create("pa_src_user", FieldDescription.FIELD_TYPE.STRING))
            .put(13, FieldDescription.create("pa_dest_user", FieldDescription.FIELD_TYPE.STRING))
            .put(14, FieldDescription.create("pa_application", FieldDescription.FIELD_TYPE.STRING))
            .put(15, FieldDescription.create("pa_virtualsys", FieldDescription.FIELD_TYPE.STRING))
            .put(16, FieldDescription.create("pa_src_zone", FieldDescription.FIELD_TYPE.STRING))
            .put(17, FieldDescription.create("pa_dest_zone", FieldDescription.FIELD_TYPE.STRING))
            .put(18, FieldDescription.create("pa_inbound_int", FieldDescription.FIELD_TYPE.STRING))
            .put(19, FieldDescription.create("pa_outbound_int", FieldDescription.FIELD_TYPE.STRING))
            .put(20, FieldDescription.create("pa_log_action", FieldDescription.FIELD_TYPE.STRING))
            .put(21, FieldDescription.create("pa_future_use0", FieldDescription.FIELD_TYPE.STRING))
            .put(22, FieldDescription.create("pa_session_id", FieldDescription.FIELD_TYPE.LONG))
            .put(23, FieldDescription.create("pa_repeat_count", FieldDescription.FIELD_TYPE.LONG))
            .put(24, FieldDescription.create("src_port", FieldDescription.FIELD_TYPE.LONG))
            .put(25, FieldDescription.create("dest_port", FieldDescription.FIELD_TYPE.LONG))
            .put(26, FieldDescription.create("nat_src_port", FieldDescription.FIELD_TYPE.LONG))
            .put(27, FieldDescription.create("nat_dest_port", FieldDescription.FIELD_TYPE.LONG))
            .put(28, FieldDescription.create("pa_flags", FieldDescription.FIELD_TYPE.STRING))
            .put(29, FieldDescription.create("protocol", FieldDescription.FIELD_TYPE.STRING))
            .put(30, FieldDescription.create("action", FieldDescription.FIELD_TYPE.STRING))
            .put(31, FieldDescription.create("pa_misc", FieldDescription.FIELD_TYPE.STRING))
            .put(32, FieldDescription.create("pa_threatID", FieldDescription.FIELD_TYPE.STRING))
            .put(33, FieldDescription.create("pa_noname", FieldDescription.FIELD_TYPE.STRING))
            .put(34, FieldDescription.create("pa_severity", FieldDescription.FIELD_TYPE.STRING))
            .put(35, FieldDescription.create("pa_direction", FieldDescription.FIELD_TYPE.STRING))
            .put(36, FieldDescription.create("pa_seqnum", FieldDescription.FIELD_TYPE.LONG))
            .put(37, FieldDescription.create("action_flags", FieldDescription.FIELD_TYPE.STRING))
            .put(38, FieldDescription.create("pa_src_location", FieldDescription.FIELD_TYPE.STRING))
            .put(39, FieldDescription.create("pa_dest_location", FieldDescription.FIELD_TYPE.STRING))
            .put(40, FieldDescription.create("future_use", FieldDescription.FIELD_TYPE.STRING))
            .put(41, FieldDescription.create("content_type", FieldDescription.FIELD_TYPE.STRING))
            .put(42, FieldDescription.create("pcap_id", FieldDescription.FIELD_TYPE.LONG))
            .put(43, FieldDescription.create("pa_file_digest", FieldDescription.FIELD_TYPE.STRING))
            .put(44, FieldDescription.create("pa_cloud", FieldDescription.FIELD_TYPE.STRING))
            .put(45, FieldDescription.create("url_index", FieldDescription.FIELD_TYPE.LONG))
            .put(46, FieldDescription.create("user_agent", FieldDescription.FIELD_TYPE.STRING))
            .put(47, FieldDescription.create("file_type", FieldDescription.FIELD_TYPE.STRING))
            .put(49, FieldDescription.create("x-forwarded-for", FieldDescription.FIELD_TYPE.STRING))
            .put(50, FieldDescription.create("http_referer", FieldDescription.FIELD_TYPE.STRING))
            .put(51, FieldDescription.create("email_sender", FieldDescription.FIELD_TYPE.STRING))
            .put(52, FieldDescription.create("email_subject", FieldDescription.FIELD_TYPE.STRING))
            .put(53, FieldDescription.create("email_recipient", FieldDescription.FIELD_TYPE.STRING))
            .put(54, FieldDescription.create("report_id", FieldDescription.FIELD_TYPE.LONG))
            .put(55, FieldDescription.create("dvc_hierarchy_l1", FieldDescription.FIELD_TYPE.LONG))
            .put(56, FieldDescription.create("dvc_hierarchy_l2", FieldDescription.FIELD_TYPE.LONG))
            .put(57, FieldDescription.create("dvc_hierarchy_l3", FieldDescription.FIELD_TYPE.LONG))
            .put(58, FieldDescription.create("dvc_hierarchy_l4", FieldDescription.FIELD_TYPE.LONG))
            .put(59, FieldDescription.create("pa_virtualsys_name", FieldDescription.FIELD_TYPE.STRING))
            .put(60, FieldDescription.create("pa_devicename", FieldDescription.FIELD_TYPE.STRING))
            .put(61, FieldDescription.create("pa_src_vm_uuid", FieldDescription.FIELD_TYPE.STRING))
            .put(62, FieldDescription.create("pa_dest_vm_uuid", FieldDescription.FIELD_TYPE.STRING))
            .put(63, FieldDescription.create("http_method", FieldDescription.FIELD_TYPE.STRING))
            .put(64, FieldDescription.create("pa_tunnel_id_imsi", FieldDescription.FIELD_TYPE.LONG))
            .put(65, FieldDescription.create("pa_monitortag_imei", FieldDescription.FIELD_TYPE.STRING))
            .put(66, FieldDescription.create("pa_parent_session_id", FieldDescription.FIELD_TYPE.LONG))
            .put(67, FieldDescription.create("pa_parent_start_time", FieldDescription.FIELD_TYPE.STRING))
            .put(68, FieldDescription.create("pa_tunnel_type", FieldDescription.FIELD_TYPE.STRING))
            .put(69, FieldDescription.create("threat_category", FieldDescription.FIELD_TYPE.STRING))
            .put(70, FieldDescription.create("pa_content_version", FieldDescription.FIELD_TYPE.STRING))
            .put(71, FieldDescription.create("future_use_end", FieldDescription.FIELD_TYPE.STRING))
            .put(72, FieldDescription.create("pa_sctp_assoc_id", FieldDescription.FIELD_TYPE.LONG))
            .put(73, FieldDescription.create("pa_payload_prot_id", FieldDescription.FIELD_TYPE.LONG))
            .put(74, FieldDescription.create("http_headers", FieldDescription.FIELD_TYPE.STRING))
            .build();

    @Override
    public ImmutableMap<Integer, FieldDescription> getMapping() {
        return MAP;
    }

}
