package org.graylog.integrations.aws;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A collection of CloudWatch log events that was generated by a Kinesis CloudWatch log subscription.
 * See for more info: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Subscriptions.html
 *
 * <p/>
 * Example payload:
 * <pre>
 * {
 *   "messageType": "DATA_MESSAGE",
 *   "owner": "123456789",
 *   "logGroup": "aws-plugin-test-flows",
 *   "logStream": "eni-aaaaaaaa-all",
 *   "subscriptionFilters": ["match-all"],
 *   "logEvents": [
 *     {
 *       "id": "33503748002479370955346306650196094071913271643270021120",
 *       "timestamp": 1502360020000,
 *       "message": "2 123456789 eni-aaaaaaaa 10.0.27.226 10.42.96.199 3604 17720 17 1 132 1502360020 1502360079 REJECT OK"
 *     },
 *     {
 *       "id": "33503748002479370955346306650196094071913271643270021127",
 *       "timestamp": 1502360020000,
 *       "message": "2 123456789 eni-aaaaaaaa 10.0.34.113 10.42.96.199 53421 17720 6 1 48 1502360020 1502360079 REJECT OK"
 *     }
 *   ]
 * }
 * </pre>
 */
public class CloudWatchLogSubscriptionData {

    @JsonProperty("messageType")
    public String messageType;

    @JsonProperty("owner")
    public String owner;

    @JsonProperty("logGroup")
    public String logGroup;

    @JsonProperty("logStream")
    public String logStream;

    @JsonProperty("subscriptionFilters")
    public List<String> subscriptionFilters;

    @JsonProperty("logEvents")
    public List<CloudWatchLogEvent> logEvents;
}
